#!/bin/bash
set -e
cd "$(dirname "$0")/../builtinFonts"
echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""
font_id() {
  ruby -rdigest -e 'puts(ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16)}.sum % (2**32) - (2**31))' "$@"
}

# Reader-font IDs hash the 3 weight-specific per-size headers plus the matching shared
# tables, so a change to either the per-size bitmap / kerning matrix or a shared
# interval / class / ligature table invalidates the on-SD font cache.
reader_shared() {
  local family=$1
  echo "./shared/${family}_regular_tables.h ./shared/${family}_bold_tables.h ./shared/${family}_italic_tables.h"
}

echo "#define CHAREINK_10_FONT_ID ($(font_id ./chareink_10_regular.h ./chareink_10_bold.h ./chareink_10_italic.h))"
echo "#define CHAREINK_12_FONT_ID ($(font_id ./chareink_12_regular.h ./chareink_12_bold.h ./chareink_12_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_13_FONT_ID ($(font_id ./chareink_13_regular.h ./chareink_13_bold.h ./chareink_13_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_14_FONT_ID ($(font_id ./chareink_14_regular.h ./chareink_14_bold.h ./chareink_14_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_15_FONT_ID ($(font_id ./chareink_15_regular.h ./chareink_15_bold.h ./chareink_15_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_16_FONT_ID ($(font_id ./chareink_16_regular.h ./chareink_16_bold.h ./chareink_16_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_17_FONT_ID ($(font_id ./chareink_17_regular.h ./chareink_17_bold.h ./chareink_17_italic.h $(reader_shared chareink)))"
echo ""
echo "#define BOOKERLY_10_FONT_ID ($(font_id ./bookerly_10_regular.h ./bookerly_10_bold.h ./bookerly_10_italic.h))"
echo "#define BOOKERLY_12_FONT_ID ($(font_id ./bookerly_12_regular.h ./bookerly_12_bold.h ./bookerly_12_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_13_FONT_ID ($(font_id ./bookerly_13_regular.h ./bookerly_13_bold.h ./bookerly_13_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_14_FONT_ID ($(font_id ./bookerly_14_regular.h ./bookerly_14_bold.h ./bookerly_14_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_15_FONT_ID ($(font_id ./bookerly_15_regular.h ./bookerly_15_bold.h ./bookerly_15_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_16_FONT_ID ($(font_id ./bookerly_16_regular.h ./bookerly_16_bold.h ./bookerly_16_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_17_FONT_ID ($(font_id ./bookerly_17_regular.h ./bookerly_17_bold.h ./bookerly_17_italic.h $(reader_shared bookerly)))"
echo ""
# Georgia: serif reader font. Sizes 10,12,13,14,15,16,17, three faces
# (Regular/Bold/Italic). No shared tables (dedup-shared-tables.py does not
# process Georgia), so each ID hashes just the three per-size headers.
for size in 10 12 13 14 15 16 17; do
  if [[ -f "./georgia_${size}_regular.h" ]]; then
    echo "#define GEORGIA_${size}_FONT_ID ($(font_id ./georgia_${size}_regular.h ./georgia_${size}_bold.h ./georgia_${size}_italic.h))"
  fi
done
echo ""
# ETbb (ET Book): serif reader font. Sizes 10,12,13,14,15,16,17, FOUR faces
# (Regular/Bold/Italic/BoldItalic). No shared tables (dedup-shared-tables.py
# does not process it), so each ID hashes the four per-size headers.
for size in 10 12 13 14 15 16 17; do
  if [[ -f "./etbb_${size}_regular.h" ]]; then
    echo "#define ETBB_${size}_FONT_ID ($(font_id ./etbb_${size}_regular.h ./etbb_${size}_bold.h ./etbb_${size}_italic.h ./etbb_${size}_bolditalic.h))"
  fi
done
echo ""
# Rosarivo: Renaissance serif reader font. Sizes 10,12,13,14,15,16,17, TWO faces
# (Regular/Italic; no Bold/BoldItalic source). No shared tables, so each ID
# hashes the two per-size headers.
for size in 10 12 13 14 15 16 17; do
  if [[ -f "./rosarivo_${size}_regular.h" ]]; then
    echo "#define ROSARIVO_${size}_FONT_ID ($(font_id ./rosarivo_${size}_regular.h ./rosarivo_${size}_italic.h))"
  fi
done
echo ""
# Lato: humanist sans-serif reader font. Sizes 10,12,13,14,15,16,17, FOUR faces
# (Regular/Bold/Italic/BoldItalic). No shared tables, so each ID hashes the four
# per-size headers.
for size in 10 12 13 14 15 16 17; do
  if [[ -f "./lato_${size}_regular.h" ]]; then
    echo "#define LATO_${size}_FONT_ID ($(font_id ./lato_${size}_regular.h ./lato_${size}_bold.h ./lato_${size}_italic.h ./lato_${size}_bolditalic.h))"
  fi
done
echo ""

# TT2020: experimental typewriter-emulation font (debug env only). Single
# size (15) with four faces. Base supplies Regular + Italic; Style E (the
# "worn" variant) stands in for Bold + BoldItalic. No shared tables.
for size in 12 13 14 15 16 17; do
  if [[ -f "./tt2020_${size}_regular.h" ]]; then
    echo "#define TT2020_${size}_FONT_ID ($(font_id \
      ./tt2020_${size}_regular.h \
      ./tt2020_${size}_bold.h \
      ./tt2020_${size}_italic.h \
      ./tt2020_${size}_bolditalic.h))"
  fi
done
echo ""
echo "#define UI_10_FONT_ID ($(font_id ./ui_10_regular.h))"
echo "#define UI_12_FONT_ID ($(font_id ./ui_12_regular.h))"
echo "#define SMALL_FONT_ID ($(font_id ./ui_8_regular.h))"
