#!/bin/bash
set -e
cd "$(dirname "$0")/../builtinFonts"
echo "// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh"
echo "#pragma once"
echo ""
font_id() {
  ruby -rdigest -e 'puts(ARGV.map{|f| Digest::SHA256.hexdigest(File.read(f)).to_i(16)}.sum % (2**32) - (2**31))' "$@"
}

# Same 32-bit reduction as font_id, but hashes the argument STRINGS instead of
# file contents. Used for the Tier-2 SD-only sizes (11/13/15/18) which have no
# flash header to hash — their id derives from the canonical weight-name set, so
# it is stable + reproducible with no file present. (A future change to such a
# font's glyphs must bump SECTION_FILE_VERSION, since the id is name-derived and
# would not otherwise invalidate the on-SD section cache.)
name_font_id() {
  ruby -rdigest -e 'puts(ARGV.map{|s| Digest::SHA256.hexdigest(s).to_i(16)}.sum % (2**32) - (2**31))' "$@"
}

# Reader-font IDs hash the 3 weight-specific per-size headers plus the matching shared
# tables, so a change to either the per-size bitmap / kerning matrix or a shared
# interval / class / ligature table invalidates the on-SD font cache.
reader_shared() {
  local family=$1
  echo "./shared/${family}_regular_tables.h ./shared/${family}_bold_tables.h ./shared/${family}_italic_tables.h"
}

echo "#define CHAREINK_10_FONT_ID ($(font_id ./chareink_10_regular.h ./chareink_10_bold.h ./chareink_10_italic.h))"
echo "#define CHAREINK_12_FONT_ID ($(font_id ./chareink_12_regular.h ./chareink_12_bold.h ./chareink_12_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_14_FONT_ID ($(font_id ./chareink_14_regular.h ./chareink_14_bold.h ./chareink_14_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_16_FONT_ID ($(font_id ./chareink_16_regular.h ./chareink_16_bold.h ./chareink_16_italic.h $(reader_shared chareink)))"
echo "#define CHAREINK_17_FONT_ID ($(font_id ./chareink_17_regular.h ./chareink_17_bold.h ./chareink_17_italic.h $(reader_shared chareink)))"
echo ""
echo "#define BOOKERLY_10_FONT_ID ($(font_id ./bookerly_10_regular.h ./bookerly_10_bold.h ./bookerly_10_italic.h))"
echo "#define BOOKERLY_12_FONT_ID ($(font_id ./bookerly_12_regular.h ./bookerly_12_bold.h ./bookerly_12_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_14_FONT_ID ($(font_id ./bookerly_14_regular.h ./bookerly_14_bold.h ./bookerly_14_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_16_FONT_ID ($(font_id ./bookerly_16_regular.h ./bookerly_16_bold.h ./bookerly_16_italic.h $(reader_shared bookerly)))"
echo "#define BOOKERLY_17_FONT_ID ($(font_id ./bookerly_17_regular.h ./bookerly_17_bold.h ./bookerly_17_italic.h $(reader_shared bookerly)))"
echo ""
# Georgia: serif reader font. Sizes 10,12,14,16,17, three faces
# (Regular/Bold/Italic). No shared tables (dedup-shared-tables.py does not
# process Georgia), so each ID hashes just the three per-size headers.
for size in 10 12 14 16 17; do
  if [[ -f "./georgia_${size}_regular.h" ]]; then
    echo "#define GEORGIA_${size}_FONT_ID ($(font_id ./georgia_${size}_regular.h ./georgia_${size}_bold.h ./georgia_${size}_italic.h))"
  fi
done
echo ""
# Lato: humanist sans-serif reader font. Sizes 10,12,14,16,17, FOUR faces
# (Regular/Bold/Italic/BoldItalic). No shared tables, so each ID hashes the four
# per-size headers.
for size in 10 12 14 16 17; do
  if [[ -f "./lato_${size}_regular.h" ]]; then
    echo "#define LATO_${size}_FONT_ID ($(font_id ./lato_${size}_regular.h ./lato_${size}_bold.h ./lato_${size}_italic.h ./lato_${size}_bolditalic.h))"
  fi
done
echo ""
# Helvetica: grotesque sans-serif reader font. Sizes 10,12,14,16,17, THREE
# faces (Regular/Bold/Italic). No shared tables, so each ID hashes the three
# per-size headers.
for size in 10 12 14 16 17; do
  if [[ -f "./helvetica_${size}_regular.h" ]]; then
    echo "#define HELVETICA_${size}_FONT_ID ($(font_id ./helvetica_${size}_regular.h ./helvetica_${size}_bold.h ./helvetica_${size}_italic.h))"
  fi
done
echo ""
# Verdana: humanist sans-serif reader font. Sizes 10,12,14,16,17, THREE
# faces (Regular/Bold/Italic). No shared tables, so each ID hashes the three
# per-size headers.
for size in 10 12 14 16 17; do
  if [[ -f "./verdana_${size}_regular.h" ]]; then
    echo "#define VERDANA_${size}_FONT_ID ($(font_id ./verdana_${size}_regular.h ./verdana_${size}_bold.h ./verdana_${size}_italic.h))"
  fi
done
echo ""

# Tier-2 SD-only extra reader sizes (11/13/15/18) for every offloadable family.
# No flash header ships for these — the glyph TABLES live in the SD .bin pack
# (see bake-sd-extra-packs.sh), so each costs ~0 flash. Their IDs hash the
# canonical weight-NAME set (name_font_id), reproducible without any file. Lato
# carries a real bold-italic; the other four synthesise it (3 names).
for size in 11 13 15 18; do
  echo "#define BOOKERLY_${size}_FONT_ID ($(name_font_id bookerly_${size}_regular bookerly_${size}_bold bookerly_${size}_italic))"
  echo "#define GEORGIA_${size}_FONT_ID ($(name_font_id georgia_${size}_regular georgia_${size}_bold georgia_${size}_italic))"
  echo "#define LATO_${size}_FONT_ID ($(name_font_id lato_${size}_regular lato_${size}_bold lato_${size}_italic lato_${size}_bolditalic))"
  echo "#define HELVETICA_${size}_FONT_ID ($(name_font_id helvetica_${size}_regular helvetica_${size}_bold helvetica_${size}_italic))"
  echo "#define VERDANA_${size}_FONT_ID ($(name_font_id verdana_${size}_regular verdana_${size}_bold verdana_${size}_italic))"
done
echo ""

# TT2020: experimental typewriter-emulation font (debug env only). Single
# size (15) with four faces. Base supplies Regular + Italic; Style E (the
# "worn" variant) stands in for Bold + BoldItalic. No shared tables.
for size in 12 13 14 15 16 17; do
  if [[ -f "./tt2020_${size}_regular.h" ]]; then
    echo "#define TT2020_${size}_FONT_ID ($(font_id \
      ./tt2020_${size}_regular.h \
      ./tt2020_${size}_bold.h \
      ./tt2020_${size}_italic.h \
      ./tt2020_${size}_bolditalic.h))"
  fi
done
echo ""
# UI font = Pixel Operator, two sizes: 16px (status, 1x grid) + 32px (body/menus/
# titles, 2x grid). Both are exact multiples of the 16px design grid so both are
# pixel-perfect and even. The 32px face carries regular + bold in one EpdFontFamily,
# so titles/selection use BOLD weight rather than a third size. UI_12 (old "title"
# size) is an alias of UI_10 — same 32px font.
echo "#define UI_10_FONT_ID ($(font_id ./ui_32_regular.h))"
echo "#define UI_12_FONT_ID UI_10_FONT_ID"
echo "#define SMALL_FONT_ID ($(font_id ./ui_16_regular.h))"
