#!/usr/bin/env python3
"""Rewrite a fontconvert builtin-font header so its bitmap blob can move to SD.

A reader-font header generated by fontconvert.py embeds the whole glyph bitmap
blob as `static const uint8_t <name>Bitmaps[N] = { ... };` in flash. For the
SD-font offload (CPBN packs streamed from the card) we want that array to compile
out under -DCROSSPOINT_SD_FONTS_SLIM while the default in-flash build stays
byte-for-byte identical. This script post-processes the header in place:

  1. wraps the first `<name>Bitmaps[N]` array in `#ifndef CROSSPOINT_SD_FONTS_SLIM`;
  2. makes the EpdFontData struct's first field (the bitmap pointer) conditional:
        #ifdef CROSSPOINT_SD_FONTS_SLIM
            nullptr,
        #else
            <name>Bitmaps,
        #endif

Post-processing (vs re-baking from TTF) is deliberate: it guarantees the glyph
tables, metrics and bitmap bytes are untouched, so there is zero render drift
between the flash build and the SD build (asset-regeneration lesson).

The transform is idempotent and also migrates headers still carrying the old
single-flag `CROSSPOINT_SD_FONTS` pilot guard to the split `_SLIM` macro. Headers
with no bitmap array (e.g. shared-tables files) are returned unchanged.

Usage:
    python3 offload_bitmaps.py header1.h header2.h ...   # rewrite in place
    python3 offload_bitmaps.py --check header.h          # exit 1 if it would change
"""
import re
import sys

SLIM = "CROSSPOINT_SD_FONTS_SLIM"

# The bitmap array: first `static const uint8_t <name>Bitmaps[N] = { ... };`.
# An optional pre-existing `#ifndef CROSSPOINT_SD_FONTS*` guard (and its trailing
# `#endif`) is captured so re-runs / old-flag migrations normalise cleanly.
_ARRAY_RE = re.compile(
    r"(?:#ifndef[ \t]+CROSSPOINT_SD_FONTS\w*[ \t]*\n)?"
    r"(static const uint8_t (\w+Bitmaps)\[\d+\] = \{.*?\n\};\n)"
    r"(?:#endif[ \t]*\n)?",
    re.DOTALL,
)


def offload_header(text: str) -> str:
    """Return `text` rewritten so the bitmap blob is SD-offloadable. Idempotent."""
    m = _ARRAY_RE.search(text)
    if not m:
        return text  # no bitmap array (shared-tables / unrelated header)
    symbol = m.group(2)  # e.g. "foo_12_regularBitmaps"

    text = _ARRAY_RE.sub(
        lambda mm: f"#ifndef {SLIM}\n{mm.group(1)}#endif\n", text, count=1
    )

    # Struct first field: either bare `    <symbol>,` or an existing conditional
    # block (any CROSSPOINT_SD_FONTS* flag). Normalise both to the _SLIM block.
    sym = re.escape(symbol)
    field_re = re.compile(
        r"(static const EpdFontData \w+ = \{\n)"
        r"(?:#ifdef[ \t]+CROSSPOINT_SD_FONTS\w*\n[ \t]*nullptr,\n#else\n[ \t]*"
        + sym
        + r",\n#endif\n"
        r"|[ \t]*" + sym + r",\n)"
    )
    text = field_re.sub(
        lambda mm: f"{mm.group(1)}#ifdef {SLIM}\n    nullptr,\n#else\n    {symbol},\n#endif\n",
        text,
        count=1,
    )
    return text


def main(argv):
    check = False
    paths = []
    for a in argv:
        if a == "--check":
            check = True
        else:
            paths.append(a)
    if not paths:
        print(__doc__)
        return 2

    changed = 0
    for path in paths:
        with open(path, "r", encoding="utf-8") as f:
            src = f.read()
        out = offload_header(src)
        if out == src:
            continue
        changed += 1
        if check:
            print(f"would rewrite: {path}")
            continue
        with open(path, "w", encoding="utf-8") as f:
            f.write(out)
        print(f"rewrote: {path}")

    if check:
        return 1 if changed else 0
    print(f"{changed} header(s) rewritten")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
