#pragma once

#include <builtinFonts/chareink_10_regular.h>
#include <builtinFonts/chareink_10_bold.h>
#include <builtinFonts/chareink_10_italic.h>
#include <builtinFonts/chareink_12_regular.h>
#include <builtinFonts/chareink_12_bold.h>
#include <builtinFonts/chareink_12_italic.h>
#include <builtinFonts/chareink_13_regular.h>
#include <builtinFonts/chareink_13_bold.h>
#include <builtinFonts/chareink_13_italic.h>
#include <builtinFonts/chareink_14_regular.h>
#include <builtinFonts/chareink_14_bold.h>
#include <builtinFonts/chareink_14_italic.h>
#include <builtinFonts/chareink_15_regular.h>
#include <builtinFonts/chareink_15_bold.h>
#include <builtinFonts/chareink_15_italic.h>
#include <builtinFonts/chareink_16_regular.h>
#include <builtinFonts/chareink_16_bold.h>
#include <builtinFonts/chareink_16_italic.h>
#include <builtinFonts/chareink_17_regular.h>
#include <builtinFonts/chareink_17_bold.h>
#include <builtinFonts/chareink_17_italic.h>

#include <builtinFonts/bookerly_10_regular.h>
#include <builtinFonts/bookerly_10_bold.h>
#include <builtinFonts/bookerly_10_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_13_regular.h>
#include <builtinFonts/bookerly_13_bold.h>
#include <builtinFonts/bookerly_13_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_15_regular.h>
#include <builtinFonts/bookerly_15_bold.h>
#include <builtinFonts/bookerly_15_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_17_regular.h>
#include <builtinFonts/bookerly_17_bold.h>
#include <builtinFonts/bookerly_17_italic.h>

#include <builtinFonts/georgia_10_regular.h>
#include <builtinFonts/georgia_10_bold.h>
#include <builtinFonts/georgia_10_italic.h>
#include <builtinFonts/georgia_12_regular.h>
#include <builtinFonts/georgia_12_bold.h>
#include <builtinFonts/georgia_12_italic.h>
#include <builtinFonts/georgia_13_regular.h>
#include <builtinFonts/georgia_13_bold.h>
#include <builtinFonts/georgia_13_italic.h>
#include <builtinFonts/georgia_14_regular.h>
#include <builtinFonts/georgia_14_bold.h>
#include <builtinFonts/georgia_14_italic.h>
#include <builtinFonts/georgia_15_regular.h>
#include <builtinFonts/georgia_15_bold.h>
#include <builtinFonts/georgia_15_italic.h>
#include <builtinFonts/georgia_16_regular.h>
#include <builtinFonts/georgia_16_bold.h>
#include <builtinFonts/georgia_16_italic.h>
#include <builtinFonts/georgia_17_regular.h>
#include <builtinFonts/georgia_17_bold.h>
#include <builtinFonts/georgia_17_italic.h>

#include <builtinFonts/pixel32_12_regular.h>
#include <builtinFonts/pixel32_12_bold.h>
#include <builtinFonts/pixel32_12_italic.h>
#include <builtinFonts/pixel32_14_regular.h>
#include <builtinFonts/pixel32_14_bold.h>
#include <builtinFonts/pixel32_14_italic.h>
#include <builtinFonts/pixel32_16_regular.h>
#include <builtinFonts/pixel32_16_bold.h>
#include <builtinFonts/pixel32_16_italic.h>

#include <builtinFonts/f25_10_regular.h>
#include <builtinFonts/f25_10_bold.h>
#include <builtinFonts/f25_10_italic.h>
#include <builtinFonts/f25_11_regular.h>
#include <builtinFonts/f25_11_bold.h>
#include <builtinFonts/f25_11_italic.h>
#include <builtinFonts/f25_12_regular.h>
#include <builtinFonts/f25_12_bold.h>
#include <builtinFonts/f25_12_italic.h>
#include <builtinFonts/f25_13_regular.h>
#include <builtinFonts/f25_13_bold.h>
#include <builtinFonts/f25_13_italic.h>
#include <builtinFonts/f25_14_regular.h>
#include <builtinFonts/f25_14_bold.h>
#include <builtinFonts/f25_14_italic.h>
#include <builtinFonts/f25_16_regular.h>
#include <builtinFonts/f25_16_bold.h>
#include <builtinFonts/f25_16_italic.h>
#include <builtinFonts/f25_17_regular.h>
#include <builtinFonts/f25_17_bold.h>
#include <builtinFonts/f25_17_italic.h>

#include <builtinFonts/ui_8_regular.h>
#include <builtinFonts/ui_10_regular.h>
#include <builtinFonts/ui_12_regular.h>
