#pragma once

#include <builtinFonts/chareink_10_regular.h>
#include <builtinFonts/chareink_10_bold.h>
#include <builtinFonts/chareink_10_italic.h>
#include <builtinFonts/chareink_12_regular.h>
#include <builtinFonts/chareink_12_bold.h>
#include <builtinFonts/chareink_12_italic.h>
#include <builtinFonts/chareink_13_regular.h>
#include <builtinFonts/chareink_13_bold.h>
#include <builtinFonts/chareink_13_italic.h>
#include <builtinFonts/chareink_14_regular.h>
#include <builtinFonts/chareink_14_bold.h>
#include <builtinFonts/chareink_14_italic.h>
#include <builtinFonts/chareink_15_regular.h>
#include <builtinFonts/chareink_15_bold.h>
#include <builtinFonts/chareink_15_italic.h>
#include <builtinFonts/chareink_16_regular.h>
#include <builtinFonts/chareink_16_bold.h>
#include <builtinFonts/chareink_16_italic.h>
#include <builtinFonts/chareink_17_regular.h>
#include <builtinFonts/chareink_17_bold.h>
#include <builtinFonts/chareink_17_italic.h>

#include <builtinFonts/bookerly_10_regular.h>
#include <builtinFonts/bookerly_10_bold.h>
#include <builtinFonts/bookerly_10_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_13_regular.h>
#include <builtinFonts/bookerly_13_bold.h>
#include <builtinFonts/bookerly_13_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_15_regular.h>
#include <builtinFonts/bookerly_15_bold.h>
#include <builtinFonts/bookerly_15_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_17_regular.h>
#include <builtinFonts/bookerly_17_bold.h>
#include <builtinFonts/bookerly_17_italic.h>

#include <builtinFonts/georgia_10_regular.h>
#include <builtinFonts/georgia_10_bold.h>
#include <builtinFonts/georgia_10_italic.h>
#include <builtinFonts/georgia_12_regular.h>
#include <builtinFonts/georgia_12_bold.h>
#include <builtinFonts/georgia_12_italic.h>
#include <builtinFonts/georgia_13_regular.h>
#include <builtinFonts/georgia_13_bold.h>
#include <builtinFonts/georgia_13_italic.h>
#include <builtinFonts/georgia_14_regular.h>
#include <builtinFonts/georgia_14_bold.h>
#include <builtinFonts/georgia_14_italic.h>
#include <builtinFonts/georgia_15_regular.h>
#include <builtinFonts/georgia_15_bold.h>
#include <builtinFonts/georgia_15_italic.h>
#include <builtinFonts/georgia_16_regular.h>
#include <builtinFonts/georgia_16_bold.h>
#include <builtinFonts/georgia_16_italic.h>
#include <builtinFonts/georgia_17_regular.h>
#include <builtinFonts/georgia_17_bold.h>
#include <builtinFonts/georgia_17_italic.h>

#include <builtinFonts/etbb_10_regular.h>
#include <builtinFonts/etbb_10_bold.h>
#include <builtinFonts/etbb_10_italic.h>
#include <builtinFonts/etbb_10_bolditalic.h>
#include <builtinFonts/etbb_12_regular.h>
#include <builtinFonts/etbb_12_bold.h>
#include <builtinFonts/etbb_12_italic.h>
#include <builtinFonts/etbb_12_bolditalic.h>
#include <builtinFonts/etbb_13_regular.h>
#include <builtinFonts/etbb_13_bold.h>
#include <builtinFonts/etbb_13_italic.h>
#include <builtinFonts/etbb_13_bolditalic.h>
#include <builtinFonts/etbb_14_regular.h>
#include <builtinFonts/etbb_14_bold.h>
#include <builtinFonts/etbb_14_italic.h>
#include <builtinFonts/etbb_14_bolditalic.h>
#include <builtinFonts/etbb_15_regular.h>
#include <builtinFonts/etbb_15_bold.h>
#include <builtinFonts/etbb_15_italic.h>
#include <builtinFonts/etbb_15_bolditalic.h>
#include <builtinFonts/etbb_16_regular.h>
#include <builtinFonts/etbb_16_bold.h>
#include <builtinFonts/etbb_16_italic.h>
#include <builtinFonts/etbb_16_bolditalic.h>
#include <builtinFonts/etbb_17_regular.h>
#include <builtinFonts/etbb_17_bold.h>
#include <builtinFonts/etbb_17_italic.h>
#include <builtinFonts/etbb_17_bolditalic.h>

#include <builtinFonts/rosarivo_10_regular.h>
#include <builtinFonts/rosarivo_10_italic.h>
#include <builtinFonts/rosarivo_12_regular.h>
#include <builtinFonts/rosarivo_12_italic.h>
#include <builtinFonts/rosarivo_13_regular.h>
#include <builtinFonts/rosarivo_13_italic.h>
#include <builtinFonts/rosarivo_14_regular.h>
#include <builtinFonts/rosarivo_14_italic.h>
#include <builtinFonts/rosarivo_15_regular.h>
#include <builtinFonts/rosarivo_15_italic.h>
#include <builtinFonts/rosarivo_16_regular.h>
#include <builtinFonts/rosarivo_16_italic.h>
#include <builtinFonts/rosarivo_17_regular.h>
#include <builtinFonts/rosarivo_17_italic.h>

#include <builtinFonts/lato_10_regular.h>
#include <builtinFonts/lato_10_bold.h>
#include <builtinFonts/lato_10_italic.h>
#include <builtinFonts/lato_10_bolditalic.h>
#include <builtinFonts/lato_12_regular.h>
#include <builtinFonts/lato_12_bold.h>
#include <builtinFonts/lato_12_italic.h>
#include <builtinFonts/lato_12_bolditalic.h>
#include <builtinFonts/lato_13_regular.h>
#include <builtinFonts/lato_13_bold.h>
#include <builtinFonts/lato_13_italic.h>
#include <builtinFonts/lato_13_bolditalic.h>
#include <builtinFonts/lato_14_regular.h>
#include <builtinFonts/lato_14_bold.h>
#include <builtinFonts/lato_14_italic.h>
#include <builtinFonts/lato_14_bolditalic.h>
#include <builtinFonts/lato_15_regular.h>
#include <builtinFonts/lato_15_bold.h>
#include <builtinFonts/lato_15_italic.h>
#include <builtinFonts/lato_15_bolditalic.h>
#include <builtinFonts/lato_16_regular.h>
#include <builtinFonts/lato_16_bold.h>
#include <builtinFonts/lato_16_italic.h>
#include <builtinFonts/lato_16_bolditalic.h>
#include <builtinFonts/lato_17_regular.h>
#include <builtinFonts/lato_17_bold.h>
#include <builtinFonts/lato_17_italic.h>
#include <builtinFonts/lato_17_bolditalic.h>

#include <builtinFonts/ui_8_regular.h>
#include <builtinFonts/ui_10_regular.h>
#include <builtinFonts/ui_12_regular.h>
