#pragma once

#include <builtinFonts/chareink_10_regular.h>
#include <builtinFonts/chareink_10_bold.h>
#include <builtinFonts/chareink_10_italic.h>
#include <builtinFonts/chareink_12_regular.h>
#include <builtinFonts/chareink_12_bold.h>
#include <builtinFonts/chareink_12_italic.h>
#include <builtinFonts/chareink_14_regular.h>
#include <builtinFonts/chareink_14_bold.h>
#include <builtinFonts/chareink_14_italic.h>
#include <builtinFonts/chareink_16_regular.h>
#include <builtinFonts/chareink_16_bold.h>
#include <builtinFonts/chareink_16_italic.h>
#include <builtinFonts/chareink_17_regular.h>
#include <builtinFonts/chareink_17_bold.h>
#include <builtinFonts/chareink_17_italic.h>

#include <builtinFonts/bookerly_10_regular.h>
#include <builtinFonts/bookerly_10_bold.h>
#include <builtinFonts/bookerly_10_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_16_regular.h>
#include <builtinFonts/bookerly_16_bold.h>
#include <builtinFonts/bookerly_16_italic.h>
#include <builtinFonts/bookerly_17_regular.h>
#include <builtinFonts/bookerly_17_bold.h>
#include <builtinFonts/bookerly_17_italic.h>

#include <builtinFonts/georgia_10_regular.h>
#include <builtinFonts/georgia_10_bold.h>
#include <builtinFonts/georgia_10_italic.h>
#include <builtinFonts/georgia_12_regular.h>
#include <builtinFonts/georgia_12_bold.h>
#include <builtinFonts/georgia_12_italic.h>
#include <builtinFonts/georgia_14_regular.h>
#include <builtinFonts/georgia_14_bold.h>
#include <builtinFonts/georgia_14_italic.h>
#include <builtinFonts/georgia_16_regular.h>
#include <builtinFonts/georgia_16_bold.h>
#include <builtinFonts/georgia_16_italic.h>
#include <builtinFonts/georgia_17_regular.h>
#include <builtinFonts/georgia_17_bold.h>
#include <builtinFonts/georgia_17_italic.h>

#include <builtinFonts/lato_10_regular.h>
#include <builtinFonts/lato_10_bold.h>
#include <builtinFonts/lato_10_italic.h>
#include <builtinFonts/lato_10_bolditalic.h>
#include <builtinFonts/lato_12_regular.h>
#include <builtinFonts/lato_12_bold.h>
#include <builtinFonts/lato_12_italic.h>
#include <builtinFonts/lato_12_bolditalic.h>
#include <builtinFonts/lato_14_regular.h>
#include <builtinFonts/lato_14_bold.h>
#include <builtinFonts/lato_14_italic.h>
#include <builtinFonts/lato_14_bolditalic.h>
#include <builtinFonts/lato_16_regular.h>
#include <builtinFonts/lato_16_bold.h>
#include <builtinFonts/lato_16_italic.h>
#include <builtinFonts/lato_16_bolditalic.h>
#include <builtinFonts/lato_17_regular.h>
#include <builtinFonts/lato_17_bold.h>
#include <builtinFonts/lato_17_italic.h>
#include <builtinFonts/lato_17_bolditalic.h>

#include <builtinFonts/helvetica_10_regular.h>
#include <builtinFonts/helvetica_10_bold.h>
#include <builtinFonts/helvetica_10_italic.h>
#include <builtinFonts/helvetica_12_regular.h>
#include <builtinFonts/helvetica_12_bold.h>
#include <builtinFonts/helvetica_12_italic.h>
#include <builtinFonts/helvetica_14_regular.h>
#include <builtinFonts/helvetica_14_bold.h>
#include <builtinFonts/helvetica_14_italic.h>
#include <builtinFonts/helvetica_16_regular.h>
#include <builtinFonts/helvetica_16_bold.h>
#include <builtinFonts/helvetica_16_italic.h>
#include <builtinFonts/helvetica_17_regular.h>
#include <builtinFonts/helvetica_17_bold.h>
#include <builtinFonts/helvetica_17_italic.h>

#include <builtinFonts/verdana_10_regular.h>
#include <builtinFonts/verdana_10_bold.h>
#include <builtinFonts/verdana_10_italic.h>
#include <builtinFonts/verdana_12_regular.h>
#include <builtinFonts/verdana_12_bold.h>
#include <builtinFonts/verdana_12_italic.h>
#include <builtinFonts/verdana_14_regular.h>
#include <builtinFonts/verdana_14_bold.h>
#include <builtinFonts/verdana_14_italic.h>
#include <builtinFonts/verdana_16_regular.h>
#include <builtinFonts/verdana_16_bold.h>
#include <builtinFonts/verdana_16_italic.h>
#include <builtinFonts/verdana_17_regular.h>
#include <builtinFonts/verdana_17_bold.h>
#include <builtinFonts/verdana_17_italic.h>

#include <builtinFonts/pixelop_48_bold.h>
#include <builtinFonts/pixelop_48_regular.h>

#include <builtinFonts/ui_16_regular.h>
#include <builtinFonts/ui_32_bold.h>
#include <builtinFonts/ui_32_regular.h>
