#!/usr/bin/env python3
"""
Allocation-seam guard (ratcheting).

The firmware is built -fno-exceptions: a bare `new T(...)` or std::vector growth
that cannot be satisfied calls abort() -> device reset, bypassing every recovery
screen. The hardening strategy routes all heap allocation through a single
fallible seam (lib/Memory/Memory.h): makeUniqueNoThrow for C++ objects/arrays,
crosspoint::mem::tryMalloc/tryRealloc/CMallocPtr for C-interop buffers. Raw
`new` (non-nothrow) and bare malloc/calloc/realloc are banned in our code.

This script is the enforcement. It is a RATCHET, not a big-bang gate: the
current known violations are recorded per-file in alloc_seam_baseline.json. The
build fails only when a file's violation count INCREASES or a new offending file
appears. As each module is migrated to the seam, its count drops; re-run with
--update to lock in the lower count so it can never regress.

Usage:
    python check_alloc_seam.py            # check (CI / pre-build); nonzero on regression
    python check_alloc_seam.py --update   # rewrite baseline from current tree

A single line may be exempted with a trailing `// alloc-ok` comment (used by the
seam helpers themselves and the rare audited C-ownership site).
"""

import json
import re
import sys
from pathlib import Path

# Repo root = parent of this script's dir (scripts/). Under PlatformIO the script
# is exec'd by SCons without __file__ set, but with cwd at the project root.
try:
    _SCRIPT_DIR = Path(__file__).resolve().parent
except NameError:
    _SCRIPT_DIR = Path.cwd() / "scripts"
ROOT = _SCRIPT_DIR.parent
BASELINE = _SCRIPT_DIR / "alloc_seam_baseline.json"

# Directories scanned for OUR code.
SCAN_DIRS = ["src", "lib"]

# Vendored / third-party trees: their allocation style is not ours to police.
EXCLUDE_DIR_PARTS = {
    "expat",
    "miniz",
    "picojpeg",
    "uzlib",
    ".pio",
}

# Files exempt entirely: the seam definition itself, and generated artifacts.
EXCLUDE_FILES = {
    "lib/Memory/Memory.h",
    "lib/I18n/I18nStrings.cpp",  # auto-generated by gen_i18n.py (gitignored)
}

SUFFIXES = {".c", ".cc", ".cpp", ".h", ".hpp"}

# Bare malloc/calloc/realloc (lowercase). The seam helpers are tryMalloc /
# tryRealloc (capital M/R) and live in the exempt Memory.h, so they never match.
RE_CALLOC = re.compile(r"\b(?:malloc|calloc|realloc)\s*\(")
# `new Type` / `new Type[...]` but NOT `new (std::nothrow) ...` and NOT
# placement-new `new (buf) Type` (the `(` after spaces fails the class-char
# requirement).
RE_NEW = re.compile(r"\bnew\s+(?!\(std::nothrow\))[A-Za-z_:~]")


RE_STR = re.compile(r'"(?:\\.|[^"\\])*"')
RE_RAW_OPEN = re.compile(r'R"([^("]*)\(')


def strip_strings_and_comment(line: str) -> str:
    # Blank out normal "..." literals, then drop any trailing // comment. Keeps
    # `new`/malloc tokens that live inside string literals (embedded web-UI JS
    # like `new Promise`, or log text like "OOM new WebServer") from registering
    # as violations. Multi-line raw strings are handled by the caller's state.
    line = RE_STR.sub('""', line)
    idx = line.find("//")
    return line if idx < 0 else line[:idx]


def count_violations(path: Path) -> int:
    n = 0
    in_raw = False
    raw_close = ""
    for raw in path.read_text(errors="replace").splitlines():
        if in_raw:
            # Inside a C++ raw string literal: skip until its )delim" terminator.
            end = raw.find(raw_close)
            if end < 0:
                continue
            raw = raw[end + len(raw_close):]
            in_raw = False
        if "// alloc-ok" in raw:
            continue
        code = strip_strings_and_comment(raw)
        # Detect an unterminated raw-string opener so following lines are skipped.
        m = RE_RAW_OPEN.search(code)
        if m:
            close = ')' + m.group(1) + '"'
            if code.find(close, m.end()) < 0:
                in_raw = True
                raw_close = close
                code = code[:m.start()]
        if RE_CALLOC.search(code):
            n += 1
        if RE_NEW.search(code):
            n += 1
    return n


def scan() -> dict:
    counts = {}
    for d in SCAN_DIRS:
        base = ROOT / d
        if not base.exists():
            continue
        for path in base.rglob("*"):
            if path.suffix not in SUFFIXES:
                continue
            rel = path.relative_to(ROOT).as_posix()
            if rel in EXCLUDE_FILES:
                continue
            if EXCLUDE_DIR_PARTS & set(path.relative_to(ROOT).parts):
                continue
            c = count_violations(path)
            if c:
                counts[rel] = c
    return counts


def main() -> int:
    update = "--update" in sys.argv
    current = scan()

    if update:
        BASELINE.write_text(json.dumps(dict(sorted(current.items())), indent=2) + "\n")
        total = sum(current.values())
        print(f"alloc-seam baseline updated: {len(current)} files, {total} violations.")
        return 0

    baseline = json.loads(BASELINE.read_text()) if BASELINE.exists() else {}

    regressions = []
    for rel, c in sorted(current.items()):
        allowed = baseline.get(rel, 0)
        if c > allowed:
            regressions.append(f"  {rel}: {c} raw allocations (baseline {allowed})")

    if regressions:
        print("Allocation-seam guard FAILED — new raw allocation(s) detected.", file=sys.stderr)
        print("Route through lib/Memory/Memory.h (makeUniqueNoThrow / tryMalloc),", file=sys.stderr)
        print("or, for an audited C-ownership site, add a `// alloc-ok` comment.", file=sys.stderr)
        print("\n".join(regressions), file=sys.stderr)
        return 1

    total = sum(current.values())
    print(f"alloc-seam guard OK: {len(current)} files at/under baseline ({total} legacy allocations remain).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
else:
    # Imported by PlatformIO as a pre: extra_script. Fail the build on regression.
    try:
        Import("env")  # noqa: F821 (provided by SCons)
        if main() != 0:
            Exit(1)  # noqa: F821 (provided by SCons)
    except NameError:
        pass
