// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define CHAREINK_10_FONT_ID (-701587092)
#define CHAREINK_12_FONT_ID (568873273)
#define CHAREINK_14_FONT_ID (-1968901116)
#define CHAREINK_16_FONT_ID (217876072)
#define CHAREINK_17_FONT_ID (-1613403261)

#define BOOKERLY_10_FONT_ID (-1756234765)
#define BOOKERLY_12_FONT_ID (1780203794)
#define BOOKERLY_14_FONT_ID (-501438826)
#define BOOKERLY_16_FONT_ID (1350175354)
#define BOOKERLY_17_FONT_ID (-354463084)

#define GEORGIA_10_FONT_ID (291611762)
#define GEORGIA_12_FONT_ID (-207815717)
#define GEORGIA_14_FONT_ID (1938199704)
#define GEORGIA_16_FONT_ID (743512669)
#define GEORGIA_17_FONT_ID (1850145980)

#define LATO_10_FONT_ID (-1295916759)
#define LATO_12_FONT_ID (649839477)
#define LATO_14_FONT_ID (1156899139)
#define LATO_16_FONT_ID (-795553796)
#define LATO_17_FONT_ID (1571067663)

#define HELVETICA_10_FONT_ID (844408219)
#define HELVETICA_12_FONT_ID (735788164)
#define HELVETICA_14_FONT_ID (1666575503)
#define HELVETICA_16_FONT_ID (463352581)
#define HELVETICA_17_FONT_ID (-2135182578)

#define VERDANA_10_FONT_ID (1852997024)
#define VERDANA_12_FONT_ID (-738185483)
#define VERDANA_14_FONT_ID (1590611299)
#define VERDANA_16_FONT_ID (1107162930)
#define VERDANA_17_FONT_ID (-171562463)


#define UI_10_FONT_ID (-551108662)
#define UI_12_FONT_ID UI_10_FONT_ID
#define SMALL_FONT_ID (-698893830)

// --- Extra reader sizes 11/13/15/18 (SD-only Tier-1: tables in flash, bitmaps in SD packs) ---
// Name-hashed (name_font_id in build-font-ids.sh); APPENDED to keep existing content-hashed
// ids stable (the committed fontIds.h predates later header edits — a clean regen would
// re-key every book's section cache; a future clean regen must bump SECTION_FILE_VERSION).
#define BOOKERLY_11_FONT_ID (-1568226765)
#define GEORGIA_11_FONT_ID (-1039436286)
#define LATO_11_FONT_ID (-664650482)
#define HELVETICA_11_FONT_ID (-384593747)
#define VERDANA_11_FONT_ID (1710894204)
#define BOOKERLY_13_FONT_ID (-1342458288)
#define GEORGIA_13_FONT_ID (-1469831864)
#define LATO_13_FONT_ID (293585460)
#define HELVETICA_13_FONT_ID (-1847257606)
#define VERDANA_13_FONT_ID (739309968)
#define BOOKERLY_15_FONT_ID (-874954626)
#define GEORGIA_15_FONT_ID (-137735079)
#define LATO_15_FONT_ID (1743376185)
#define HELVETICA_15_FONT_ID (-1985027492)
#define VERDANA_15_FONT_ID (743450860)
#define BOOKERLY_18_FONT_ID (-2093482358)
#define GEORGIA_18_FONT_ID (233400001)
#define LATO_18_FONT_ID (-770132080)
#define HELVETICA_18_FONT_ID (943921862)
#define VERDANA_18_FONT_ID (2114719867)

// --- Merriweather + Playfair Display (SD-only Tier-1 families: tables in flash, bitmaps in SD packs) ---
// Brand-new families, so EVERY size is name-hashed (name_font_id in build-font-ids.sh) and
// APPENDED here — same stable-id rule as the extra-size block above. Both carry a real
// bold-italic instance (4 weight names hashed per id). Sizes 10..18, all SD-gated in main.cpp.
#define MERRIWEATHER_10_FONT_ID (474655552)
#define MERRIWEATHER_11_FONT_ID (-606843941)
#define MERRIWEATHER_12_FONT_ID (-980914712)
#define MERRIWEATHER_13_FONT_ID (-830270881)
#define MERRIWEATHER_14_FONT_ID (506990549)
#define MERRIWEATHER_15_FONT_ID (-1015801518)
#define MERRIWEATHER_16_FONT_ID (1378690)
#define MERRIWEATHER_17_FONT_ID (-1787212573)
#define MERRIWEATHER_18_FONT_ID (1957572858)
#define PLAYFAIR_10_FONT_ID (-969321885)
#define PLAYFAIR_11_FONT_ID (493939792)
#define PLAYFAIR_12_FONT_ID (-501493939)
#define PLAYFAIR_13_FONT_ID (-818259531)
#define PLAYFAIR_14_FONT_ID (-1393258150)
#define PLAYFAIR_15_FONT_ID (1294861658)
#define PLAYFAIR_16_FONT_ID (573896367)
#define PLAYFAIR_17_FONT_ID (-820597265)
#define PLAYFAIR_18_FONT_ID (-1912081502)

// --- Galmuri (SD-only PIXEL family; native crisp sizes 14px=1x + 28px=2x, 3 weights) ---
// Name-hashed + APPENDED (stable-id rule). The reader maps the 10..18 size scale onto
// these two native pixel sizes (10..15 -> 14, 16..18 -> 28); a pixel font has no crisp
// in-between sizes. Bold-italic synthesised (3 weight names hashed).
#define GALMURI_14_FONT_ID (-412052972)
#define GALMURI_28_FONT_ID (1316825346)

// --- Vollkorn (SD-only Tier-1 serif family; sizes 10..18, 4 real weights, real kerning) ---
#define VOLLKORN_10_FONT_ID (1993148124)
#define VOLLKORN_11_FONT_ID (1379963285)
#define VOLLKORN_12_FONT_ID (1159099680)
#define VOLLKORN_13_FONT_ID (1530087009)
#define VOLLKORN_14_FONT_ID (-852618491)
#define VOLLKORN_15_FONT_ID (745130094)
#define VOLLKORN_16_FONT_ID (-537170164)
#define VOLLKORN_17_FONT_ID (-1872023147)
#define VOLLKORN_18_FONT_ID (-1379873034)
