// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh
#pragma once

#define CHAREINK_10_FONT_ID (-701587092)
#define CHAREINK_12_FONT_ID (568873273)
#define CHAREINK_14_FONT_ID (-1968901116)
#define CHAREINK_16_FONT_ID (217876072)
#define CHAREINK_17_FONT_ID (-1613403261)

#define BOOKERLY_10_FONT_ID (-1756234765)
#define BOOKERLY_12_FONT_ID (1780203794)
#define BOOKERLY_14_FONT_ID (-501438826)
#define BOOKERLY_16_FONT_ID (1350175354)
#define BOOKERLY_17_FONT_ID (-354463084)

#define GEORGIA_10_FONT_ID (291611762)
#define GEORGIA_12_FONT_ID (-207815717)
#define GEORGIA_14_FONT_ID (1938199704)
#define GEORGIA_16_FONT_ID (743512669)
#define GEORGIA_17_FONT_ID (1850145980)

#define LATO_10_FONT_ID (-1295916759)
#define LATO_12_FONT_ID (649839477)
#define LATO_14_FONT_ID (1156899139)
#define LATO_16_FONT_ID (-795553796)
#define LATO_17_FONT_ID (1571067663)

#define HELVETICA_10_FONT_ID (844408219)
#define HELVETICA_12_FONT_ID (735788164)
#define HELVETICA_14_FONT_ID (1666575503)
#define HELVETICA_16_FONT_ID (463352581)
#define HELVETICA_17_FONT_ID (-2135182578)

#define VERDANA_10_FONT_ID (1852997024)
#define VERDANA_12_FONT_ID (-738185483)
#define VERDANA_14_FONT_ID (1590611299)
#define VERDANA_16_FONT_ID (1107162930)
#define VERDANA_17_FONT_ID (-171562463)


#define UI_10_FONT_ID (-551108662)
#define UI_12_FONT_ID UI_10_FONT_ID
#define SMALL_FONT_ID (-698893830)

// --- Tier-2 SD-only extra reader sizes (11/13/15/18) ---
// No flash header ships for these (glyph tables live in the SD .bin pack, see
// lib/EpdFont/scripts/bake-sd-extra-packs.sh). IDs hash the canonical weight-NAME
// set (name_font_id in build-font-ids.sh), so they are stable + reproducible with
// no header file. Appended rather than regenerated to avoid re-keying the existing
// content-hashed ids (the committed fontIds.h predates later header edits).
#define BOOKERLY_11_FONT_ID (-1568226765)
#define GEORGIA_11_FONT_ID (-1039436286)
#define LATO_11_FONT_ID (-664650482)
#define HELVETICA_11_FONT_ID (-384593747)
#define VERDANA_11_FONT_ID (1710894204)
#define BOOKERLY_13_FONT_ID (-1342458288)
#define GEORGIA_13_FONT_ID (-1469831864)
#define LATO_13_FONT_ID (293585460)
#define HELVETICA_13_FONT_ID (-1847257606)
#define VERDANA_13_FONT_ID (739309968)
#define BOOKERLY_15_FONT_ID (-874954626)
#define GEORGIA_15_FONT_ID (-137735079)
#define LATO_15_FONT_ID (1743376185)
#define HELVETICA_15_FONT_ID (-1985027492)
#define VERDANA_15_FONT_ID (743450860)
#define BOOKERLY_18_FONT_ID (-2093482358)
#define GEORGIA_18_FONT_ID (233400001)
#define LATO_18_FONT_ID (-770132080)
#define HELVETICA_18_FONT_ID (943921862)
#define VERDANA_18_FONT_ID (2114719867)
